Description: Main Template
Mappings:
  AMIFromRegion:
    us-east-1:
      NatAMI: ami-4868ab25
    us-east-2:
      NatAMI: ami-92a6fef7
    eu-west-1:
      NatAMI: ami-a8dd45db
    us-west-1:
      NatAMI: ami-004b0f60
    us-west-2:
      NatAMI: ami-a275b1c2
    ap-south-1:
      NatAMI: ami-e2b9d38d
    ap-northeast-2:
      NatAMI: ami-d14388bf
    ap-southeast-1:
      NatAMI: ami-a79b49c4
    ap-southeast-2:
      NatAMI: ami-53371f30
    ap-northeast-1:
      NatAMI: ami-2443b745
    eu-central-1:
      NatAMI: ami-5825cd37
    sa-east-1:
      NatAMI: ami-9336bcff
Parameters:
  1VPCCIDR:
    Type: String
    Description: IP Address range for Management VPC
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.0.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  2ESCIDR1:
    Type: String
    Description: Must be inside VPC CIDR
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.0.0/28
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: 'ESCIDR was renamed to ESCIDR1. Must be inside VPC CIDR.
    Subnet in which the shells and commands execution servers are created. '
  2ESCIDR2:
    Type: String
    Description: Must be inside VPC CIDR. Optional when HighAvailabilityMode is False.
    MinLength: '0'
    MaxLength: '18'
    Default: 10.0.0.16/28
    AllowedPattern: '^$|(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: '(Mandatory when HighAvailabilityMode is enabled)
    Must be inside VPC CIDR. Subnet in which the fallback shells and commands execution
    servers are created.'
  6VPNAddress:
    Type: String
    Description: IP Address of your router
    MinLength: '7'
    MaxLength: '15'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})'
    ConstraintDescription: must be a valid IP address of the form x.x.x.x
  5OnPremiseCIDR:
    Type: String
    Description: IP Address address range of a network behind the router
    MinLength: '9'
    MaxLength: '18'
    Default: 192.168.1.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  ZServerIP:
    Type: String
    Description: IP Address of your CloudShell Server
    MinLength: '7'
    MaxLength: '15'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})'
    ConstraintDescription: must be a valid IP address of the form x.x.x.x
  3NATCIDR:
    Type: String
    Description: Must be inside VPC CIDR
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.0.32/28
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: 'must be a valid IP CIDR range of the form x.x.x.x/x, inside VPC CIDR'
  7KeyPair:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: Choose the Keypair for the instances
  4QualiCIDR:
    Type: String
    Description: Must be inside VPC CIDR
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.0.48/28
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: 'must be a valid IP CIDR range of the form x.x.x.x/x, inside VPC CIDR'
  8InstanceType:
    Type: String
    Description: >-
      The instance type to be used for the Execution Server and QuailX
      instances. The minimum recommended instance type is c4.xlarge.
    Default: c4.xlarge
  9HighAvailabilityMode:
    Type: String
    Description: ''
    Default: 'True'
    AllowedValues:
      - 'True'
      - 'False'
  10UseTransitGateway:
    Type: String
    Description: '(Applies to AWS 2G shell, mandatory for shared VPC mode) Creates the
    transit gateway. Set to True if you want to work in shared VPC mode.'
    Default: 'False'
    AllowedValues:
      - 'True'
      - 'False'
  ZUsername:
    Type: String
    Description: Username for CloudShell server
  ZPassword:
    Type: String
    Description: Password for CloudShell server
    NoEcho: true
  ShareAccountId:
    Type: String
    Default: ''
    Description: '(Applies to AWS 2G shell, mandatory for shared VPC mode) ID of the
    AWS account to be used for shared VPC deployments. There are two ways to share
    a transit gateway with the account, by specifying the Account ID here or by
    manually sharing the Transit Gateway with the account, as explained in this
    AWS documentation page:
    https://docs.aws.amazon.com/vpc/latest/tgw/tgw-transit-gateways.html#tgw-sharing.
    Note: Associating additional shared VPCs with the account is done manually. '
  UseNAT:
    Type: String
    Description: Use NAT or not
    Default: 'True'
    AllowedValues:
      - 'True'
      - 'False'
  EnhanceS3BucketSecurity:
    Type: String
    Description: Enable encryption for the bucket and block public access
    Default: 'False'
    AllowedValues:
      - 'True'
      - 'False'
Conditions:
  IsHighAvailabilityMode: !Equals
    - !Ref 9HighAvailabilityMode
    - 'True'
Resources:
  AMILookup:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://kyrylo-test.s3-eu-west-1.amazonaws.com/AMI_Lookup.json'
      Parameters:
        LookupLatestWindowsServerAmi: 'False'
        LookupLatestCentosAmi: 'True'
  VPCNAT:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://kyrylo-test.s3-eu-west-1.amazonaws.com/1_VPC.yaml'
      Parameters:
        VPCCIDR: !Ref 1VPCCIDR
        ESCIDR1: !Ref 2ESCIDR1
        ESCIDR2: !Ref 2ESCIDR2
        VPNAddress: !Ref 6VPNAddress
        OnPremiseCIDR: !Ref 5OnPremiseCIDR
        ServerIP: !Ref ZServerIP
        NATCIDR: !Ref 3NATCIDR
        KeyPair: !Ref 7KeyPair
        QualiCIDR: !Ref 4QualiCIDR
        AZ1: !Select
          - '0'
          - !GetAZs
            Ref: 'AWS::Region'
        AZ2: !If
          - IsHighAvailabilityMode
          - !Select
            - '1'
            - !GetAZs
              Ref: 'AWS::Region'
          - 'NULL'
        HA: !Ref 9HighAvailabilityMode
        NatAMI: !FindInMap
          - AMIFromRegion
          - !Ref 'AWS::Region'
          - NatAMI
        UseTransitGateway: !Ref 10UseTransitGateway
        ShareAccountId: !Ref ShareAccountId
        EnhanceS3BucketSecurity: !Ref EnhanceS3BucketSecurity
        UseNAT: !Ref UseNAT
  Instances:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        QualixSN: !GetAtt
          - VPCNAT
          - Outputs.QualixSN
        ESInstanceSN1: !GetAtt
          - VPCNAT
          - Outputs.ESInstanceSN1
        ESInstanceSN2: !GetAtt
          - VPCNAT
          - Outputs.ESInstanceSN2
        QualiXInstanceProfile: !GetAtt
          - VPCNAT
          - Outputs.QualiXInstanceProfile
        ESInstanceProfile: !GetAtt
          - VPCNAT
          - Outputs.ESInstanceProfile
        SG1id: !GetAtt
          - VPCNAT
          - Outputs.SG1id
        SG2id: !GetAtt
          - VPCNAT
          - Outputs.SG2id
        QualixAMI: !GetAtt
          - AMILookup
          - Outputs.CentosAMI
        ESAMI: !GetAtt
          - AMILookup
          - Outputs.CentosAMI
        KeyPair: !Ref 7KeyPair
        ESInstance2Profile: !GetAtt
          - VPCNAT
          - Outputs.ESInstance2Profile
        ServerIP: !Ref ZServerIP
        ZUsername: !Ref ZUsername
        ZPassword: !Ref ZPassword
        InstanceSize: !Ref 8InstanceType
      TemplateURL: 'https://kyrylo-test.s3-eu-west-1.amazonaws.com/2_EC2.yaml'
Outputs:
  ManagementVPCID:
    Description: Management VPC ID
    Value: !GetAtt
      - VPCNAT
      - Outputs.VPCId
  SG1id:
    Description: SG1 ID
    Value: !GetAtt
      - VPCNAT
      - Outputs.SG1id
  S3Name:
    Description: Name of S3 bucket
    Value: !GetAtt
      - VPCNAT
      - Outputs.S3Name
  QualixInstanceIP:
    Description: Internal IP of QualiX instance
    Value: !GetAtt
      - Instances
      - Outputs.QualixInstanceIP
