Description: 'Shared VPC, subnets, security groups'
Parameters:
  VPCCIDR:
    Type: String
    Description: IP Address range for Shared VPC
    MinLength: '9'
    MaxLength: '18'
    Default: 10.1.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  DefaultSubnetCIDR:
    Type: String
    Description: Must be inside VPC CIDR
    MinLength: '9'
    MaxLength: '18'
    Default: 10.1.254.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: 'must be a valid IP CIDR range of the form x.x.x.x/x, inside VPC CIDR'
  VPNAddress:
    Type: String
    Description: IP Address of your router
    MinLength: '7'
    MaxLength: '15'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})'
    ConstraintDescription: must be a valid IP address of the form x.x.x.x
  TransitGWid:
    Type: String
  ManagementAccountId:
    Type: String
Resources:
  SharedVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      InstanceTenancy: default
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: CloudShellSharedVPC
        - Key: CreateBy
          Value: CloudShell
      CidrBlock: !Ref VPCCIDR
  DefaultSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref SharedVPC
      CidrBlock: !Ref DefaultSubnetCIDR
      Tags:
        - Key: Name
          Value: Default Subnet
        - Key: CreateBy
          Value: CloudShell
  CSExecutionServerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
              AWS:
                - !Ref ManagementAccountId
            Action:
              - 'sts:AssumeRole'
      Path: /
  CSExecutionServerInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref CSExecutionServerRole
  CSExecutionServerRWPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: CSExecutionServerRWPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 'ec2:*'
            Resource: '*'
      Roles:
        - !Ref CSExecutionServerRole
  SharedIGW:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: CreateBy
          Value: CloudShell
  SharedIGWAttachement:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref SharedIGW
      VpcId: !Ref SharedVPC
  VPNGw:
    Type: 'AWS::EC2::VPNGateway'
    Properties:
      Type: ipsec.1
      Tags:
        - Key: Name
          Value: CloudShell_VPNGateway
        - Key: CreateBy
          Value: CloudShell
    DependsOn: CustomerGateway
  VPNConnectionVGW:
    Type: 'AWS::EC2::VPNConnection'
    Properties:
      Type: ipsec.1
      StaticRoutesOnly: 'true'
      Tags:
        - Key: Name
          Value: CloudShell_VPNGateway
        - Key: CreateBy
          Value: CloudShell
      CustomerGatewayId: !Ref CustomerGateway
      VpnGatewayId: !Ref VPNGw
  SharedVPNGwAttachement:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpnGatewayId: !Ref VPNGw
      VpcId: !Ref SharedVPC
    DependsOn: VPNGw
  CustomerGateway:
    Type: 'AWS::EC2::CustomerGateway'
    Properties:
      Type: ipsec.1
      BgpAsn: '64000'
      Tags:
        - Key: Name
          Value: Cloudshell_CustomerGateway
        - Key: CreateBy
          Value: CloudShell
      IpAddress: !Ref VPNAddress
  SharedTGWAttachment:
    Type: 'AWS::EC2::TransitGatewayAttachment'
    Properties:
      SubnetIds:
        - !Ref DefaultSubnet
      Tags:
        - Key: Name
          Value: SharedVPCAttachement
        - Key: CreateBy
          Value: CloudShell
      TransitGatewayId: !Ref TransitGWid
      VpcId: !Ref SharedVPC
Outputs:
  SharedVPCId:
    Description: VPCId of the newly created Shared VPC
    Value: !Ref SharedVPC
