Description: 'Shared VPC, subnets, security groups'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Parameters:
        - VPCCIDR
        - DefaultSubnetCIDR
        - VPNAddress1
        - VPNAddress2
        - TransitGWid
        - ESRoleArn
    ParameterLabels:
      VPCCIDR:
        default: Shared VPC CIDR
      DefaultSubnetCIDR:
        default: Default subnet CIDR
      VPNAddress1:
        default: 1st VPN address
      VPNAddress2:
        default: 2nd VPN address
      TransitGWid:
        default: Transit Gateway Id
      ESRoleArn:
        default: Execution Server Role Arn
Parameters:
  VPCCIDR:
    Type: String
    Description: VPC CIDR for the shared VPC. Default is 10.1.0.0/16.
    MinLength: '9'
    MaxLength: '18'
    Default: 10.1.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  DefaultSubnetCIDR:
    Type: String
    Description: 'The subnet would be used to connect TGW. This CIDR range must be
    included in the defined VPC CIDR. Default is 10.1.254.0/24.'
    MinLength: '9'
    MaxLength: '18'
    Default: 10.1.254.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: 'must be a valid IP CIDR range of the form x.x.x.x/x, inside VPC CIDR'
  VPNAddress1:
    Type: String
    Description: The 1st public IP address of the router on the network in which Quali Server resides.
    MinLength: '7'
    MaxLength: '15'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})'
    ConstraintDescription: must be a valid IP address of the form x.x.x.x
  VPNAddress2:
    Type: String
    Description: The 2nd public IP address of the router on the network in which Quali Server resides.
    MinLength: '7'
    MaxLength: '15'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})'
    ConstraintDescription: must be a valid IP address of the form x.x.x.x
  TransitGWid:
    Type: String
    Description: 'ID of the transit gateway. To find the transit gateway id, open the
    CloudFormation stack that has "VPCNAT" in its name, click the Outputs tab and copy
    the TGWid value.'
  ESRoleArn:
    Type: String
    Description: Arn of the ESRole
Resources:
  SharedVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      InstanceTenancy: default
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: CloudShellSharedVPC
        - Key: CreateBy
          Value: CloudShell
      CidrBlock: !Ref VPCCIDR
  DefaultSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref SharedVPC
      CidrBlock: !Ref DefaultSubnetCIDR
      Tags:
        - Key: Name
          Value: Default Subnet
        - Key: CreateBy
          Value: CloudShell
  CSExecutionServerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
              AWS:
                - !Ref ESRoleArn
            Action:
              - 'sts:AssumeRole'
      Path: /
  CSExecutionServerRWPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: CSExecutionServerRWPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 'ec2:*'
            Resource: '*'
          - Effect: Allow
            Action: 'iam:PassRole'
            Resource: !Ref ESRoleArn
      Roles:
        - !Ref CSExecutionServerRole
  SharedIGW:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: CreateBy
          Value: CloudShell
  SharedIGWAttachement:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref SharedIGW
      VpcId: !Ref SharedVPC
  VPNGw:
    Type: 'AWS::EC2::VPNGateway'
    Properties:
      Type: ipsec.1
      Tags:
        - Key: Name
          Value: CloudShell_VPNGateway
        - Key: CreateBy
          Value: CloudShell
  VPNConnectionVGW1:
    Type: 'AWS::EC2::VPNConnection'
    Properties:
      Type: ipsec.1
      Tags:
        - Key: Name
          Value: CloudShell_VPNGateway VPN Connection 1
        - Key: CreateBy
          Value: CloudShell
      CustomerGatewayId: !Ref CustomerGateway1
      VpnGatewayId: !Ref VPNGw
  VPNConnectionVGW2:
    Type: 'AWS::EC2::VPNConnection'
    Properties:
      Type: ipsec.1
      Tags:
        - Key: Name
          Value: CloudShell_VPNGateway VPN Connection 2
        - Key: CreateBy
          Value: CloudShell
      CustomerGatewayId: !Ref CustomerGateway2
      VpnGatewayId: !Ref VPNGw
  SharedVPNGwAttachement:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpnGatewayId: !Ref VPNGw
      VpcId: !Ref SharedVPC
  CustomerGateway1:
    Type: 'AWS::EC2::CustomerGateway'
    Properties:
      Type: ipsec.1
      BgpAsn: '64000'
      Tags:
        - Key: Name
          Value: Cloudshell_CustomerGateway1
        - Key: CreateBy
          Value: CloudShell
      IpAddress: !Ref VPNAddress1
  CustomerGateway2:
    Type: 'AWS::EC2::CustomerGateway'
    Properties:
      Type: ipsec.1
      BgpAsn: '64000'
      Tags:
        - Key: Name
          Value: Cloudshell_CustomerGateway2
        - Key: CreateBy
          Value: CloudShell
      IpAddress: !Ref VPNAddress2
  SharedTGWAttachment:
    Type: 'AWS::EC2::TransitGatewayAttachment'
    Properties:
      SubnetIds:
        - !Ref DefaultSubnet
      Tags:
        - Key: Name
          Value: SharedVPCAttachement
        - Key: CreateBy
          Value: CloudShell
      TransitGatewayId: !Ref TransitGWid
      VpcId: !Ref SharedVPC
Outputs:
  SharedVPCId:
    Description: VPCId of the newly created Shared VPC
    Value: !Ref SharedVPC
  SharedVpcRoleArn:
    Description: Shared VPC Role Arn
    Value: !GetAtt CSExecutionServerRole.Arn
  VPNGWid:
    Description: VPN gateway ID
    Value: !Ref VPNGw
